// Localization
export const SET_LANGUAGE = 'SET_LANGUAGE';

// TODO form
export const GET_TODO_FORM = 'GET_TODO_FORM';
export const GET_TODO_FORM_SUCCESS = 'GET_TODO_FORM_SUCCESS';
export const GET_TODO_FORM_FAILURE = 'GET_TODO_FORM_FAILURE';
export const UPDATE_TODO_FORM = 'UPDATE_TODO_FORM';
export const UPDATE_TODO_FORM_SUCCESS = 'UPDATE_TODO_FORM_SUCCESS';
export const UPDATE_TODO_FORM_FAILURE = 'UPDATE_TODO_FORM_FAILURE';
export const RESET_TODO_FORM = 'RESET_TODO_FORM';

// TODOs list
export const GET_TODOLIST_LIST = 'GET_TODOLIST_LIST';
export const GET_TODOLIST_LIST_SUCCESS = 'GET_TODOLIST_LIST_SUCCESS';
export const GET_TODOLIST_LIST_FAILURE = 'GET_TODOLIST_LIST_FAILURE';
export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';
export const UPDATE_TODO_LIST = 'UPDATE_TODO_LIST';
export const UPDATE_TODO_LIST_SUCCESS = 'UPDATE_TODO_LIST_SUCCESS';
export const UPDATE_TODO_LIST_FAILURE = 'UPDATE_TODO_LIST_FAILURE';

// notifications
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
